ALTER TABLE users ADD date_format NVARCHAR(8) NOT NULL DEFAULT 'MDY';
ALTER TABLE users ADD time_format NVARCHAR(8) NOT NULL DEFAULT '24';
ALTER TABLE users ADD timezone NVARCHAR(64) NOT NULL DEFAULT 'UTC';
