-- put your custom database views here
-- use "GO" between SQL Server view statements; simple statements can also use ";"+newline

-- example:
-- DROP VIEW IF EXISTS AdminControllerList;
-- GO
-- CREATE VIEW AdminControllerList AS
-- select
--   *
-- , [SomeNumber]*3.14 as CalculatedField
-- from some_table
-- GO
