// Log Types model class
// store types of log for activity_logs table
// there are 2 types of logs:
// - system logs - auto-generated by fw
//   - example: added/updated/deleted (i.e. changes to entity records)
// - user logs - user-generated
//   - example: user comments, user events
//
// Part of ASP.NET osa framework  www.osalabs.com/osafw/asp.net
// (c) 2009-2024 Oleg Savchuk www.osalabs.com

namespace osafw;

public class FwLogTypes : FwModel
{
    public const int ITYPE_SYSTEM = 0;
    public const int ITYPE_USER = 10;

    public const string ICODE_ADDED = "added";
    public const string ICODE_UPDATED = "updated";
    public const string ICODE_DELETED = "deleted";
    public const string ICODE_COMMENT = "comment";
    //users login audit realted
    public const string ICODE_USERS_SIMULATE = "simulate";
    public const string ICODE_USERS_LOGIN = "login";
    public const string ICODE_USERS_LOGIN_FAIL = "login_fail";
    public const string ICODE_USERS_LOGOFF = "logoff";
    public const string ICODE_USERS_CHPWD = "chpwd";
    //cron
    public const string ICODE_CRON_JOB_RUN_START = "cron_job_run_start";
    public const string ICODE_CRON_JOB_RUN_END = "cron_job_run_end";
    public const string ICODE_CRON_JOB_MANUAL_RUN_START = "cron_job_manual_run_start";
    public const string ICODE_CRON_JOB_MANUAL_RUN_END = "cron_job_manual_run_end";
    public const string ICODE_CRON_JOB_RUN_ERROR = "cron_job_run_error";
    public const string ICODE_CRON_JOB_RUN_RESULT = "cron_job_run_result";

    public FwLogTypes() : base()
    {
        table_name = "log_types";
    }
}