// Log Types model class
// store types of log for activity_logs table
// there are 2 types of logs:
// - system logs - auto-generated by fw
//   - example: added/updated/deleted (i.e. changes to entity records)
// - user logs - user-generated
//   - example: user comments, user events
// 
// Part of ASP.NET osa framework  www.osalabs.com/osafw/asp.net
// (c) 2009-2023 Oleg Savchuk www.osalabs.com

namespace osafw;

public class LogTypes : FwModel
{
    public LogTypes() : base()
    {
        table_name = "log_types";
    }
}